# Generated by Django 5.1.4 on 2025-02-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='application_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Not Started', max_length=20),
        ),
    ]
