# Generated by Django 5.1.4 on 2025-02-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='extracurriculars',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
