# Generated by Django 5.1.4 on 2025-02-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_extracurriculars_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
